Test for 1-my_list.py
-------------------------------------------

Case 0: Importing
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry


-------------------------------------------

Case 1: Given cases.

>>> bg = BaseGeometry()
>>> bg.integer_validator("my_int", 12)

>>> bg.integer_validator("width", 89)

>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
    	...
TypeError: name must be an integer

>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
		...
ValueError: age must be greater than 0

>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
		...
ValueError: distance must be greater than 0

-------------------------------------------

Case 2: Passing a digit string.

>>> bg.integer_validator("Mohamed", "5")
Traceback (most recent call last):
    	...
TypeError: Mohamed must be an integer

-------------------------------------------

Case 3: Passing less than 2 args to the method.

>>> bg.integer_validator("ALX")
Traceback (most recent call last):
		...
TypeError: BaseGeometry.integer_validator() missing 1 required positional argument: 'value'

-------------------------------------------

Case 4: Passing more than 2 args to the method.

>>> bg.integer_validator("ALX", "best", "School", 9)
Traceback (most recent call last):
		...
TypeError: BaseGeometry.integer_validator() takes 3 positional arguments but 5 were given

-------------------------------------------

Case 5: Passing no args to the method.

>>> bg.integer_validator()
Traceback (most recent call last):
		...
TypeError: BaseGeometry.integer_validator() missing 2 required positional arguments: 'name' and 'value'

-------------------------------------------

Case 6: Passing None to the method.

>>> bg.integer_validator("ALX", None)
Traceback (most recent call last):
		...
TypeError: ALX must be an integer

-------------------------------------------

Case 7: Passing list to the method.

>>> bg.integer_validator("ALX", [1, 2, 3])
Traceback (most recent call last):
		...
TypeError: ALX must be an integer

-------------------------------------------

Case 8: Passing Boolean to the method.

>>> bg.integer_validator("ALX", False)
Traceback (most recent call last):
		...
TypeError: ALX must be an integer

-------------------------------------------

Case 9: Passing tuple to the method.

>>> bg.integer_validator("ALX", (1, 2, 3))
Traceback (most recent call last):
		...
TypeError: ALX must be an integer

-------------------------------------------

Case 10: Passing dict to the method.

>>> bg.integer_validator("ALX", {"Mohamed": 1, "Student": 2})
Traceback (most recent call last):
		...
TypeError: ALX must be an integer
